name: Level 4 - Toad's Treasure House

on:
  workflow_dispatch: {}

jobs:
  artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-MART.jar
          path: build/libs/*.jar

      # TODO - Build parameters toevoegen (hint: niet hier)

      # TODO - Produceer een build artifact (JAR) met Gradle

      # TODO - Upload het artifact met een meegegeven naam
